# Generated by Django 4.2.5 on 2024-06-29 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("assignees", models.TextField(verbose_name="Исполнители")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Назначана"),
                            ("IN_PROGRESS", "Выполняется"),
                            ("PAUSED", "Приостановлена"),
                            ("COMPLETED", "Завершена"),
                        ],
                        db_index=True,
                        default="ASSIGNED",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "planned_effort",
                    models.IntegerField(
                        default=0, verbose_name="Плановая трудоемкость"
                    ),
                ),
                (
                    "time_fact",
                    models.IntegerField(
                        default=0, verbose_name="Фактическое выполнение"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата заверщения"
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
