# Generated by Django 4.2.5 on 2024-07-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="total_planned_effort",
            field=models.IntegerField(
                default=0, verbose_name="Общая плановая трудоемкость"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="total_time_fact",
            field=models.IntegerField(
                default=0, verbose_name="Общее фактическое выполнение"
            ),
        ),
    ]
