# Generated by Django 4.2.5 on 2024-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_total_planned_effort_task_total_time_fact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
    ]
